service:
  name: yack-worker-ses

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 512
  region: us-west-2

functions:
  receiver:
    handler: handler.receiver
    memorySize: 512
    timeout: 10
    environment:
      API_PATH: ${env:API_PATH}
